default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  username: <%= ENV['QUOTATIONS_DATABASE_USERNAME'] %>
  password: <%= ENV['QUOTATIONS_DATABASE_PASSWORD'] %>

development:
  <<: *default
  host: <%= ENV['QUOTES_DB_HOST'] %>
  database: <%= ENV['QUOTATIONS_DB_NAME'] %>

test:
  <<: *default
  host: localhost
  database: <%= ENV['QUOTATIONS_DB_NAME'] %>

dev:
  host: <%= ENV['QUOTATIONS_DEV_DATABASE_HOST'] %>
  adapter: postgresql
  database: <%= ENV['QUOTATIONS_DEV_DATABASE_NAME'] %>
  encoding: utf8
  pool: 5
  port: 5432
  username: <%= ENV['QUOTATIONS_DEV_DATABASE_USERNAME'] %>
  password: <%= ENV['QUOTATIONS_DEV_DATABASE_PASSWORD'] %>

production:
  host: <%= ENV['QUOTATIONS_PROD_DATABASE_HOST'] %>
  database: <%= ENV['QUOTATIONS_PROD_DATABASE_NAME'] %>
  adapter: postgresql
  encoding: utf8
  pool: 5
  port: 5432
  username: <%= ENV['QUOTATIONS_PROD_DATABASE_USERNAME'] %>
  password: <%= ENV['QUOTATIONS_PROD_DATABASE_PASSWORD'] %>
