AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2
  Include:
  - 'config.ru'
  - 'Gemfile'
  - 'Guardfile'

  Exclude:
  - 'app/views/**/*'
  - 'bin/*'
  - 'db/schema.rb'
  - 'db/migrate/*'
  - 'log/**/*'
  - 'node_modules/**/*'
  - 'public/**/*'
  - 'scripts/**/*'
  - 'vendor/**/*'
  - 'tmp/**/*'
  - '.git/**/*'

Documentation:
  Enabled: false

IndentationConsistency:
  EnforcedStyle: 'rails'

Rails:
  Enabled: true

StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
  - './*_helper.rb'
